---
- hosts: all
  vars:
    repo: https://github.com/skyshaper/satq.git
    env:
      RAILS_ENV: production
      PATH: "{{path}}"
  tasks:
    - name: get/update source
      git: repo={{repo}} dest={{ target }}
    - name: install dependencies
      command: "bundle install --deployment --without=development,test --path=vendor/bundle chdir={{target}}"
      environment: env
    - name: make schema.rb writable
      file: "path={{target}}/db/schema.rb owner=satq"
    - name: check if database exists
      command: "./bin/rake db:version chdir={{target}}"
      environment: env
      ignore_errors: True
      register: rake_db_version_result
      sudo_user: satq
    - name: create database
      command: "./bin/rake db:setup chdir={{target}}"
      environment: env
      when: rake_db_version_result|failed
      sudo_user: satq
    - name: apply database migrations
      command: "./bin/rake db:migrate chdir={{target}}"
      environment: env
      when: rake_db_version_result|success
      sudo_user: satq
    - name: make schema.rb no longer writable
      file: "path={{target}}/db/schema.rb owner=root"
    - name: precompile assets
      command: "./bin/rake assets:precompile chdir={{target}}"
      environment: env
    - name: restart service
      command: "/command/svc -t {{service}}"
