---
- hosts: all
  vars:
    repo: https://github.com/skyshaper/satq.git
    env: 
      RAILS_ENV: production
      PATH: "{{path}}"
  tasks:
    - name: get/update source
      git: repo={{repo}} dest={{ target }}
    - name: install dependencies
      command: "bundle install --deployment --without=development,test --path=vendor/bundle chdir={{target}}"
      environment: env
    - name: check if database exists
      command: "./bin/rake db:version chdir={{target}}"
      environment: env
      ignore_errors: True
      register: rake_db_version_result
    - name: create database
      command: "./bin/rake db:setup chdir={{target}}"
      environment: env
      when: rake_db_version_result|failed
    - name: apply database migrations
      command: "./bin/rake db:migrate chdir={{target}}"
      environment: env
      when: rake_db_version_result|success
    - name: precompile assets
      command: "./bin/rake assets:precompile chdir={{target}}"
      environment: env
    - name: restart service
      command: "svc -t {{service}}"
